### ISSUE TITLE
Mirador build issue - incorrect paths for fonts and logos

### ISSUE THREAD

**Issue by pobocks** [IIIF/mirador#435] opened 2015-02-26 15:08 UTC
When I run `grunt`, the `mirador-combined.min.css` produced has an incorrect path for Fontawesome. 

Instead of `../fonts/fontawesome-whatever`, I get `../font/fontawesome-whatever`.  This only shows up in the minified CSS - non-minified seems correct.  I've verified this on my local machine (OSX), and on a CentOS VM. 

Not sure what is causing this - I've been investigating upward into grunt-contrib-cssmin and cleancss.  The `rebase: false` and `cleancss: false` options don't make a difference.

**Comment by aeschylus** [comment] 2015-03-10 17:20
Hi @pobocks, I have been unable to reproduce this in a fresh build. Which ref/hash were you building from?

**Comment by pobocks** [comment] 2015-03-10 17:44
Still happening on tip of master as of this morning.

**Comment by rsinghal** [comment] 2016-05-19 21:00
@pobocks This is (actually) fixed in `release2.1`.  Please re-open if it isn't.

**Closed by rsinghal** 2016-05-19 21:00 UTC

**Comment by pobocks** [comment] 2016-05-19 22:31
Ooooh! I'm sick home, but I'll test this Monday! Thanks!

**Comment by pobocks** [comment] 2016-05-19 23:35
I got antsy - definitely fixed!
