### ISSUE TITLE
[2.0] Ranges

### ISSUE THREAD

**Issue by azaroth42** [IIIF/mirador#94] opened 2014-07-07 23:14 UTC
Support for 2.0 Range definition, which makes it much easier to construct nested ToCs etc, as opposed to the 1.0 definition which was ... underspecified to put it mildly.
In particular, see:
* http://iiif.io/api/presentation/2.0/#ranges
* http://iiif.io/api/presentation/2.0/#technical-properties for the definitions of the range related viewing_hint values

**Comment by rsinghal** [comment] 2016-06-24 19:54
duplicate of #527

**Closed** 2016-08-12 22:55 UTC
Labels: specification, table of contents
