### ISSUE TITLE
Support right to left reading in all views

### ISSUE THREAD

**Issue by snydman** [IIIF/mirador#307] opened 2014-10-23 11:55 UTC
Following the viewing hint if present. 

Should manifest itself wherever there is horizontal navigation:
- film strip
- navigation buttons
- scroll view

**Comment by rsinghal** [comment] 2015-03-05 19:29
duplicate of #419

**Comment by rsinghal** [comment] 2015-08-11 18:14
duplicate of #419

**Closed by rsinghal** 2015-08-11 18:14 UTC
Labels: high priority, osd-collections, specification
