### ISSUE TITLE
Synchronous XMLHttpRequest on the main thread is deprecated

### ISSUE THREAD

**Issue by poornima09** [IIIF/mirador#805] opened 2016-03-25 09:47 UTC
Hello,

I am using opencart version 2.1.0.2 and my domain  is everyone.desi in this after all customization i'm facing problem on Synchronous XMLHttpRequest  ,in google chrome console its showing issue  "Synchronous XMLHttpRequest on the main thread is deprecated " so how can rectify this issue
![capture123](https://cloud.githubusercontent.com/assets/13720372/14042071/87f0e828-f29c-11e5-83d8-7b80b7476918.PNG)

Thanks

**Comment by rsinghal** [comment] 2016-03-29 19:09
Duplicate of #388

**Closed** 2016-05-24 19:54 UTC
Labels: duplicate
