### ISSUE TITLE
table of contents top entries no longer seem to be showing child ranges

### ISSUE THREAD

**Issue by jeffreycwitt** [IIIF/mirador#976] opened 2016-06-24 13:28 UTC
After pulling in latest version of 2.1 release, I'm getting an error when clicking on a table of contents item. I would expect the the table of contents item to toggle and entries for ranges contained within this parent range to appear.

To recreate the problem use this branch: https://github.com/jeffreycwitt/mirador/tree/feature/2.1-search-within and then try any of the manifests that show a table of contents.

console error reads:

`uncaught TypeError: Cannot read property '0' of undefined`

error points me to an error somewhere in this block of the code:

```
_this.element.find('.toc-link').on('click', function(event) {
        event.stopPropagation();

        var rangeID = jQuery(this).data().rangeid,
            canvasID = jQuery.grep(_this.structures, function(item) { return item['@id'] == rangeID; })[0].canvases[0],
            isLeaf = jQuery(this).closest('li').hasClass('leaf-item');

        _this.eventEmitter.publish('SET_CURRENT_CANVAS_ID.' + _this.windowId, canvasID);
      });
```

**Comment by thehabes** [comment] 2016-06-24 14:38
See #939 
I implemented a fix to make mine work in the meantime if you want it.

**Comment by aeschylus** [comment] 2016-06-24 22:27
Thanks @jeffreycwitt. Looks like an oversight in the Mirador Hackathon refactor. I'll have a look at it (and write a test for this).

**Comment by rsinghal** [comment] 2016-07-08 16:54
duplicate of #939

**Closed by rsinghal** 2016-07-08 16:54 UTC
Labels: bug, ready, table of contents
