### ISSUE TITLE
"no method slice of undefined" issue still exists when there is no TOC on an object. 

### ISSUE THREAD

**Issue by aeschylus** [IIIF/mirador#190] opened 2014-08-19 21:37 UTC

**Comment by rsinghal** [comment] 2015-04-14 14:59
Seems to have reappeared.  To duplicate, try one of these manifests:

http://scta.info/iiif/pp-sorb/manifest
http://scta.info/iiif/pdt-bnf14556/manifest
http://scta.info/iiif/pg-lon/manifest
http://scta.info/iiif/pl-bnf15705/manifest

**Comment by aeschylus** [comment] 2015-05-07 14:33
All of these manifests have the property that they have dozens of ranges with no top-level range. This seems like a strange use of ranges, but I suppose it ought to be handled. We don't really have a design for multiple ranges yet though. 

When we were first doing ranges and TOC, we made some "requirement" that there needed to be a top-level range. I have a design in mind for multiple ranges, but this use of ranges: no hierarchy and one page per range, seems like a misunderstanding of ranges.

**Comment by aeschylus** [comment] 2015-05-07 14:34
Sadly, there doesn't seem to be any way to control this because the spec is fairly silent on the issue. 200 1-item ranges with no grouping is perfectly valid.

**Comment by jeffreycwitt** [comment] 2015-06-04 15:10
Hmm, so maybe I'm not quite understanding, but I think http://scta.info/iiif/pg-lon/manifest does have a top level.

First there is the top level range: "http://scta.info/iiif/pg-lon/range/r1" which includes under the canvas property includes all the canvases in array, like so: 
"canvases": [
        "http://scta.info/iiif/pg-lon/canvas/L11v",
        "http://scta.info/iiif/pg-lon/canvas/L12r",
        "http://scta.info/iiif/pg-lon/canvas/L12v",
        "http://scta.info/iiif/pg-lon/canvas/L13r",
        "http://scta.info/iiif/pg-lon/canvas/L13v",
        "http://scta.info/iiif/pg-lon/canvas/L14r",
        "http://scta.info/iiif/pg-lon/canvas/L14v",
        "http://scta.info/iiif/pg-lon/canvas/L15r",
        "http://scta.info/iiif/pg-lon/canvas/L15v",
        "http://scta.info/iiif/pg-lon/canvas/L16r",
        "http://scta.info/iiif/pg-lon/canvas/L16v",
        "http://scta.info/iiif/pg-lon/canvas/L17r",
        "http://scta.info/iiif/pg-lon/canvas/L17v",
        ....

and so on.

Then there is a sub level range that identifies itself with the top level range, like so:
{
      "@id": "http://scta.info/iiif/pg-lon/range/r1-1",
      "within": "http://scta.info/iiif/pg-lon/range/r1",
      "@type": "sc:Range",
      "label": "Quaestio 1",
      "viewingHint": "top",
      "canvases": [
        "http://scta.info/iiif/pg-lon/canvas/L11v",
        "http://scta.info/iiif/pg-lon/canvas/L12r",
        "http://scta.info/iiif/pg-lon/canvas/L12v",
        "http://scta.info/iiif/pg-lon/canvas/L13r",
        "http://scta.info/iiif/pg-lon/canvas/L13v",
        "http://scta.info/iiif/pg-lon/canvas/L14r",
        "http://scta.info/iiif/pg-lon/canvas/L14v",
        "http://scta.info/iiif/pg-lon/canvas/L15r"
      ]
    },

Is this wrong? It seems correct and its validating perfectly. However, when you click on a given range label, no navigation occurs.

Whereas navigation for this manifest http://scta.info/iiif/pp-sorb/manifest works well.

Disregard 
     http://scta.info/iiif/pl-bnf15705/manifest
     http://scta.info/iiif/pl-bnf15705/manifest
because these aren't validating.

**Comment by thehabes** [comment] 2015-08-20 19:39
This is happening because mirador is having trouble building the bottom panel on the first focused image of the range when it is loaded, and usually only when there is one range to load (with no parent, just one range.).

I had to alter toc.js to allow for there to be a range with no parents:

In the init in toc.js:

this.element = jQuery(this.template({ ranges: this.getTplData() })).appendTo(this.appendTo);

has trouble because getTplData() does this:

ranges = _this.extractRangeTrees(_this.ranges)
if (ranges.length < 2) {
        ranges = ranges[0].children; //Why do this?  It doesn't make sense here.  
}
return ranges;

This usually causes ranges to be null which I believe causes the 'splice of undefined' error down the road when building out the bottom panel.  ranges is an array of range objects.  Even if the length is 1, we still want an array of one range object to be returned, so there is no need to alter ranges. I commented out if(ranges.length<2){...} block of code, and everything seems to be running smoothly.  I have two ranges that are disconnected without parents that both load to the view and can be navigated to and navigated through and I do not have the 'splice of undefined' error anymore and the bottom panel thumbnail images load (and to connect this with my previous work, even when they are non-IIIF images and thumbnails are not defined with the object).

**Comment by rsinghal** [comment] 2015-10-07 19:51
@jeffreycwitt I am looking into this some more.  For http://scta.info/iiif/pg-lon/manifest, I think the issue is that you don't have individual leaf nodes for each canvas that is in a range.

For example, you have the range:
```
{
 @id: "http://scta.info/iiif/pg-lon/range/r1-1",
 within: "http://scta.info/iiif/pg-lon/range/r1",
 @type: "sc:Range",
 label: "Quaestio 1",
 canvases: [
  "http://scta.info/iiif/pg-lon/canvas/L11v",
  "http://scta.info/iiif/pg-lon/canvas/L12r",
  "http://scta.info/iiif/pg-lon/canvas/L12v",
  "http://scta.info/iiif/pg-lon/canvas/L13r",
  "http://scta.info/iiif/pg-lon/canvas/L13v",
  "http://scta.info/iiif/pg-lon/canvas/L14r",
  "http://scta.info/iiif/pg-lon/canvas/L14v",
  "http://scta.info/iiif/pg-lon/canvas/L15r"
 ]
}
```

But there needs to be a range for each canvas that indicates that it is within the higher level range.  So something like:
```
{
 @id: "http://scta.info/iiif/pg-lon/range/r1-1-1",
 within: "http://scta.info/iiif/pg-lon/range/r1-1",
 @type: "sc:Range",
 label: "L11v",
 canvases: [
  "http://scta.info/iiif/pg-lon/canvas/L11v"
 ]
},
{
 @id: "http://scta.info/iiif/pg-lon/range/r1-1-2",
 within: "http://scta.info/iiif/pg-lon/range/r1-1",
 @type: "sc:Range",
 label: "L12r",
 canvases: [
  "http://scta.info/iiif/pg-lon/canvas/L12r"
 ]
},
...
```

Mirador can then show which canvases belong to Quaestio 1 in the side panel, and have the canvas in the TOC can match the canvas in the bottom filmstrip while in ImageView.

**Comment by azaroth42** [comment] 2015-10-07 20:08
That would be a bug in Mirador, however, rather than a requirement from the specification.  The top example is the way that ranges are intended and specified to work.

See: http://iiif.io/api/presentation/2.0/#ranges

**Comment by jeffreycwitt** [comment] 2015-10-07 22:47
I can try that, but a range for each canvas seems redundant. Isn't it kind of overkill to say that a canvas is a range composed of one canvas? What else could it be?

Anyway, it seems to work without problem in the universalviewer: 

http://universalviewer.azurewebsites.net/?jsonp=false&testids=false&defaultToFullScreen=false&manifest=http%3A%2F%2Fscta.info%2Fiiif%2Fpg-lon%2Fmanifest&locale=en-GB#?c=0&m=0&s=0&cv=296&z=0.0136%2C-0.0395%2C1.9729%2C1.3826

It does seem to be very strange and elusive problem. Some ranges in some manifests seem to be working fine and others are not. But all of them are machine generated by the same code. So their different behavior is confusing.

**Comment by rsinghal** [comment] 2015-10-08 15:23
I agree, I will make sure the TOC works with a valid range.  Adding leaf nodes will offer more functionality that is built into Mirador, but should not be necessary for the basic TOC to be viewable.

**Comment by rsinghal** [comment] 2015-10-08 15:42
Actually, this has nothing to do with the leaf nodes.  There are some canvases that are not referenced in the range and the TOC code is trying to scroll to a non-existent range.  This will be fixed in master momentarily.

**Closed** 2015-10-08 15:43 UTC
Labels: bug, in progress

**Comment by jeffreycwitt** [comment] 2015-10-08 15:44
Awesome,
Thanks.
jw
-- 
Dr. Jeffrey C. Witt
Philosophy Department
Loyola University Maryland
4501 N. Charles St.
Baltimore, MD 21210
www.jeffreycwitt.com <http://www.jeffreycwitt.com/>

From:  Rashmi Singhal <notifications@github.com>
Reply-To:  IIIF/mirador
<reply+00117f3d82743f9381a538287ce60f575c03bf79ab2cc66692cf00000001122e50e89
2a169ce026c1c79@reply.github.com>
Date:  Thursday, October 8, 2015 at 11:42 AM
To:  IIIF/mirador <mirador@noreply.github.com>
Cc:  Jeffrey Witt <jeffreycwitt@gmail.com>
Subject:  Re: [mirador] "no method slice of undefined" issue still exists
when there is no TOC on an object.  (#190)


Actually, this has nothing to do with the leaf nodes.  There are some
canvases that are not referenced in the range and the TOC code is trying to
scroll to a non-existent range.  This will be fixed in master momentarily.


Reply to this email directly or view it on GitHub
<https://github.com/IIIF/mirador/issues/190#issuecomment-146583094> .
